# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('role', models.CharField(blank=True, choices=[('0', '\u65e0'), ('1', '\u603b\u76d1'), ('2', '\u7ecf\u7406'), ('3', '\u7814\u53d1')], default='0', max_length=1, verbose_name='\u89d2\u8272')),
            ],
        ),
    ]
