# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('update_time', models.DateField(auto_now=True, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
                ('update_time', models.DateField(auto_now=True, null=True)),
                ('city', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Publish'),
        ),
    ]
