# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180218_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='mem_total',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
