# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180218_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='image_id',
            new_name='ami_id',
        ),
    ]
