# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180218_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterModelTable(
            name='assets',
            table='assets',
        ),
        migrations.AlterModelTable(
            name='flavor',
            table='flavor',
        ),
    ]
