# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180218_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
