# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180218_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor', to='assets.Flavor', verbose_name='\u5b9e\u4f8b\u6a21\u677f'),
        ),
    ]
